version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: demo-db
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
    ports:
      - "5432:5432"
    volumes:
      - demo_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U demo -d demo"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: .
    container_name: demo-app
    environment:
      SPRING_PROFILES_ACTIVE: docker
      # можно переопределить JDBC, если нужно:
      # SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/demo
      # SPRING_DATASOURCE_USERNAME: demo
      # SPRING_DATASOURCE_PASSWORD: demo
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  demo_pg_data:
